spring.application.name=gestion
server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/patrimoine_db
spring.data.mongodb.database=patrimoine_db
app.upload.dir=uploads/biens/

jwt.secret=ZmQ0YzZkZDI5N2JkNDZmMjhkNWQwMmI0MTlmZGE3YzM1NDk1YjQzMWVjYjJiZjM4MGMyNTNjYmM2NTZiMjQxOQ==
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG
logging.level.com.patrimoine=DEBUG

