spring.application.name=gestion
server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/patrimoine_db
spring.data.mongodb.database=patrimoine_db

jwt.secret=IWqryEBgl5nytkvSiDEARmyeoPrKlnRWKChxNlKDjLG0Bsbw3UeXEWAtHE9LnFkjjeinu7Ky/+r1uREiyJQeHw==

jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG
logging.level.com.patrimoine=DEBUG